// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnVKcA3tG7VFZs7ma-hHbbpDf0oNq-Q80',
    appId: '1:478277801915:web:df01b6110123738370d69e',
    messagingSenderId: '478277801915',
    projectId: 'smart-attendance-2ce78',
    authDomain: 'smart-attendance-2ce78.firebaseapp.com',
    storageBucket: 'smart-attendance-2ce78.appspot.com',
    measurementId: 'G-4X72RLQ1C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWqd9w5NzF1dxM624TATbXHAkcid14ql0',
    appId: '1:478277801915:android:c05a8d04deb5d62170d69e',
    messagingSenderId: '478277801915',
    projectId: 'smart-attendance-2ce78',
    storageBucket: 'smart-attendance-2ce78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2TZKO3okh8pB8i6UhXguure8n1weV6s',
    appId: '1:478277801915:ios:cfcc9327cbff3c6f70d69e',
    messagingSenderId: '478277801915',
    projectId: 'smart-attendance-2ce78',
    storageBucket: 'smart-attendance-2ce78.appspot.com',
    iosBundleId: 'com.testing.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2TZKO3okh8pB8i6UhXguure8n1weV6s',
    appId: '1:478277801915:ios:4f02d516c580b15470d69e',
    messagingSenderId: '478277801915',
    projectId: 'smart-attendance-2ce78',
    storageBucket: 'smart-attendance-2ce78.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnVKcA3tG7VFZs7ma-hHbbpDf0oNq-Q80',
    appId: '1:478277801915:web:58bdc29584d6979670d69e',
    messagingSenderId: '478277801915',
    projectId: 'smart-attendance-2ce78',
    authDomain: 'smart-attendance-2ce78.firebaseapp.com',
    storageBucket: 'smart-attendance-2ce78.appspot.com',
    measurementId: 'G-ZFZ5N8NDS3',
  );
}
